---
title: "Simulation Techniques FRM Examples"
author: "JDM"
output:
  pdf_document: default
  html_document:
    df_print: paged
subtitle: Exercises compilation for academic porpuses, Simulation Techniques Financial
  Risk Management. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Info
This file shows the result of some exercises in "ExercisesCompFRMbook.R"

### Brownian Motion p15


```{r, echo=FALSE, warning=FALSE, message=FALSE}
par(mfrow=c(2,2)) 
BMsim <- function(npaths, nSamples){
  p <- npaths
  N <- nSamples
  y <- matrix(rep(0, (N+1)*p),nrow = N+1)
  t <- (c(0:N))/N
  for (j in 1: p){
    z <- rnorm(N,0,1)
    y[1,j] <- 0
    for (i in 1:N){
      y[i + 1,j] <- (1/sqrt(N))*sum(z[1:i])
    }
  }
  matplot(t, y, type = "l", xlab = "t", ylab = "Brownian Motion", lty = 1, col = 1)
}
BMsim(1,1000)
BMsim(5,1000)
BMsim(20,1000)
BMsim(100,1000)
```

### Excercise pg149


Basket options are often valued by assuming that the value of the portfolio of assets comprising
follows the Black-Scholes dynamics jointly rather than each assetfollows the B&S individually.

```{r , echo=FALSE, warning=FALSE, message=FALSE}
#### simulate the historical stock price ####
n <-250;  r<- 0.05; dt <- 1/n;
sigma <- c(0.4,0.3,0.35);
SIGMA <- matrix(c(1,0.3,0.3,0.3,1,0.3,0.3,0.3,1),3,3);
SIGMA <- SIGMA * ( sigma %*% t (sigma) )

S <- matrix(0,3,n+1);
S[,1] <- c(100,90,80);
for (i in 1:n) {
  S[, i+1] <- S[, i] *exp(r*dt+rnorm(3)%*%chol(SIGMA) *sqrt(dt)); 
}
P <- S[1,]+S[2,]+S[3,] ; 
print(P)
returnS <- diff(t(log(S))); 
returnP <- diff(log(P));

cor(returnS) 
A <- var(returnS)/dt
B <- var(returnP)/dt
C <- S[,n+1]

time <-(0:n)/n;
range <-c(min(S)*0.5,max(S)*1.2);

plot(time,S[1,], type = "l",xlim=c(0,1.6), ylim=range, ylab = "stock price") 
lines(time,S[2,], type = "l")
lines(time,S[3,], type = "l")
lines(c(1,1), range,type = "l")

#### cont’d #####
range <- c(min(S)*0.5,max(S)*1.6);
plot(time,S[1,], type = "l",xlim=c(0,1.6), ylim = range, ylab = "stock price") 
lines(time,S[2,], type = "l")
lines(time,S[3,], type = "l")
lines(c(1,1),range,type = "l") 
print(C)


#### simulate scenarios ### 
K <- 250; t <- 0.5;
d1 <- (log(sum(C)/K)+(r+B^2/2)*t)/sqrt(B*t);
d2 <- d1-sqrt(B*t);
sum(C)*pnorm(d1)-K*exp(-r*t)*pnorm(d2);

N <- 20000;
S <- matrix(0,N,3); 
S[,1] <- C[1]; S[,2] <- C[2]; S[,3] <- C[3];

for (i in 1:125){
S <- S*exp(r*dt+matrix(rnorm(3*N) ,N,3)%*%chol(A)*sqrt(dt)) ;
}

P <- S[,1]+S[,2]+S[,3] ;
price <- exp(-r*T)*pmax(P-K,0);
mean(price)

for (i in 1:20) {
lines(c(1,1.5),c(C[1],S[i,1]),type = "l") 
lines(c(1,1.5),c(C[2],S[i,2]),type = "l") 
lines(c(1,1.5),c(C[3],S[i,3]),type = "l") 
}
```


